# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: CARLOS MD
google_analytics: CARLOS MD
title: CARLOS MD

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Carlos MD - Blog

description: Stylish Jekyll Theme
author:
  name: carlos md
  email: cfmedeiros@ufrn.edu.br
  github: camfilho
  twitter: camfilho
  #  pinterest: asd123
  #linkedin: asd123
  bio: Welcome back
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://pbs.twimg.com/profile_images/1175030104365371395/UGijiaWq_400x400.jpg

BASE_PATH:

plugins:
  - jekyll-paginate
